export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/clients/clients";
export * from "@/pages/dashboard/projets/projets";
export * from "@/pages/dashboard/users/users";
export * from "@/pages/dashboard/etat/etatavancement";
export * from "@/pages/dashboard/facture/facture";